name = "GroebnerTac"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["GroebnerTac"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "groebner"
scope = "WuProver"
rev = "fb6681985b9ebba0a74b2f57466ce2acba3f498e"

[[require]]
name = "MonomialOrderedPolynomial"
git = "https://github.com/rshlyakh/MonomialOrderedPolynomial"
rev = "fd1079f9318a6b915ca8413dc0b43f485fb40d18"

[[lean_lib]]
name = "GroebnerTac"
